### ISSUE TITLE
Chart Component

### ISSUE THREAD

**Issue by steveoni** [opensource9ja/Data-aRT#1]
We want to be able to create different charts from any data obtained

## Task

* [ ] Create `chart` component which obtains props containing `data` the type of chart and some necessary props needed for the chart plotting
* [ ] Make chart component div dragable
* [ ] `SidePlane` component should always show when a component is clicked
* [ ] Data (.csv or json) can be read using `danfojs` and default `dtype` of each column can be used to create default charts as required
* [ ] There can be a set of buttons to which users can select the type of chart
* [ ] `UseEffect` can be use to load default data for experimentation for now
* [ ] `useReducer` can be used to manage different charts created 
```js
  const defaultState = {
  chart: [{ x:"", y:"", chartType:""}], // contains charts props for each chart
};
```

## Tools
* [ ] [dimple.js](http://dimplejs.org/) I prefer this though
* [ ] [chart.js](https://www.chartjs.org/)
